### ISSUE TITLE
Add icon to node title

### ISSUE THREAD

**Issue by andrey-zakharov** [ricklupton/d3-sankey-diagram#15]
How to?
with old d3-sankey it was possible.

**Comment by ricklupton** [comment]
What kind of icon do you want? You can select all the nodes and add to them using d3 (`svg.selectAll('.node')` or similar -- have a look in the DOM inspector to see the structure that's created). Does that help?

**Comment by andrey-zakharov** [comment]
yes, comes with exact same solution today, thanx :)
