### ISSUE TITLE
Display link values

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/d3-sankey-diagram#2]
As raised in ricklupton/ipysankeywidget#5

We would like to [optionally] add text elements to the links to show the magnitude/type of the link on the diagram. Currently you can only see this by hovering to show the tooltip.

[Here is the right function to modify](https://github.com/ricklupton/d3-sankey-diagram/blob/master/src/link.js#L13-L36)

New contributors are very welcome -- we can help you. Reply below if you are interested.

**Comment by mingchau** [comment]
Hi,

My project also needs this feature, could you please let us know if there is any news to share on this?

**Comment by ricklupton** [comment]
I'm planning to work on this during the next couple of weeks, hopefully there will be some news soon!

**Comment by ricklupton** [comment]
Added in 32991f4, released in v0.7.3
