### ISSUE TITLE
Allow customizing the link title

### ISSUE THREAD

**Issue by dvdbng** [ricklupton/d3-sankey-diagram#5]
I'm aware you can customize part of the link title using `linkTypeTitle` but I couldn't find a way of completely configuring the link title.

**Comment by ricklupton** [comment]
Thanks for the comment! This is now possible in the new version (0.6) of d3-sankey-diagram using the [`.linkTitle`](https://github.com/ricklupton/d3-sankey-diagram#linkTitle) setter. There's also a function [`d3.sankeyLinkTitle`](https://github.com/ricklupton/d3-sankey-diagram#sankeyLinkTitle) to help generate suitable functions.
