### ISSUE TITLE
Remove unused code from linkPath.js

### ISSUE THREAD

**Issue by linhuiw** [ricklupton/d3-sankey-diagram#8]
excuse me, when i read the source code.
i wonder why `if (true) {...} else {...}`?
test code?

https://github.com/ricklupton/d3-sankey-diagram/blob/d254b32ae90ddb29482f184e66b385b4d931751d/src/linkPath.js#L119-L141

**Comment by ricklupton** [comment]
No very good reason - I think some testing code that accidentally got left in. We should tidy it up.

**Comment by linhuiw** [comment]
Ok, understand.  tks for you answer

**Comment by ricklupton** [comment]
I'll leave it open as this code should be tidied up sometime

**Comment by ricklupton** [comment]
New contributors are very welcome -- we can help you get started, just asks below.

**Comment by ricklupton** [comment]
Closed by #12, thanks @svwielga4!
